workflows:
  build-android:
    name: Build Android APK
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
